### PR TITLE
General rust improvements

### LINKED ISSUE #18: Rust codegen doesn't handle the `any` type.
## Actual

When trying to codegen anything with an `any` type, the Rust codegen fails with an error.

```shell-session
$ apex generate
Generating src/generated.rs...
Generation error: Unhandled primitive type conversion for type: any 
```

## Expected

Codegen to work without error.

## To reproduce

Use the following apex source.

```apexlang
namespace "issue"

type MyStruct {
  this: any
}
```

And any config that uses the rust codegen, e.g.

```yaml title="apex.yaml"
spec: ./issue.apexlang
generates:
  src/generated.rs:
    module: "@apexlang/codegen/rust"
    visitorClass: RustBasic
```

And run `apex generate`

### PR DESCRIPTION
**Pull request by jsoverson**
This PR fixes issues found during the waPC migration.
- exports all the specific visitors
- exports utils
- Fixes #18

### CODE REVIEW

File: src/rust/rust-basic.ts [hunk 1]
```diff
@@ -7,41 +7,40 @@ import {
...
+import { visibility } from "./utils/index.js";
 
 export class RustBasic extends ContextWriter {
   constructor(writer: Writer) {
     super(writer);
   }
 
   visitType(context: Context): void {
-    this.append(new StructVisitor(context).toString());
+    this.append(new StructVisitor(context.type, context).toString());
```
Comment (pkedy) [inline src/rust/rust-basic.ts:19]: Why not only pass in `context` here? Obviously `type` is enclosed in `context`.

Comment (jsoverson) [reply src/rust/rust-basic.ts:19]: The waPC codegen had a spot where it dynamically created an AST node from a callback and instantiated a visitor from there. Rather than decipher the intent was, it was easier and more extensible to make the AST node arg explicit.

**Review by pkedy — APPROVED** [review]
